### PR TITLE
fix(config): divide single config into 2 parts

### PR DESCRIPTION
**Pull request by shovanmaity**
Divide single config `config/localdevice/metac.yaml` into 2 parts.
1. `config/localdevice/cspc-v1.yaml` -> This controller will manage v1 cspc creation and deletion.
2. `config/localdevice/cspc-v1alpha1.yaml` -> This controller will manage v1alpha1 cspc creation and deletion.

NOTE - If we use single config then we need to ensure that both `v1` and `v1alpha1` CSPC CRD are present. To make it working independently with a single version(CSPC) or both the versions(CSPC) we need to divide single config into 2 parts.

### CODE REVIEW

**Comment by AmitKumarDas** [comment]
@shovanmaity dont we have to update the manifests in form of RBAC.
Will a user be able to use this DAO without director with whatever docs / manifest are provided in this repo?

**Comment by AmitKumarDas** [comment]
@shovanmaity I am little bit confused on the PR message. How was it possible to have a single config & yet create v1 or v1alpha1 resources? Leaving aside the CRD aspect how was it possible to create respective cspc resources with a single config?

**Comment by shovanmaity** [comment]
> @shovanmaity don't we have to update the manifests in the form of RBAC.

No @AmitKumarDas,  as we have `"*"` in `apiGroup`

> Will a user be able to use this DAO without director with whatever docs / manifest are provided in this repo?

No @AmitKumarDas, need to update the doc with cspc version label.

**Comment by shovanmaity** [comment]
> @shovanmaity I am little bit confused on the PR message. How was it possible to have a single config & yet create v1 or v1alpha1 resources? Leaving aside the CRD aspect how was it possible to create respective cspc resources with a single config?

:point_down: 
> How was it possible to have a single config & yet create v1 or v1alpha1 resources?

While testing I had both the crds(`v1` and `v1alpha1`) of CSPC for that it was working with single config file.

If we create 2 config files it will run as 2 controllers. If we create 1 config file it will run as 1 controller so if any crd is missing it will be stuck.

If the system has only `v1` of `CSPC` and metacontroller has 2 config files it will be able to create `v1`  `CSPC`

If the system has only `v1alpha1` of `CSPC` and metacontroller has 2 config files it will be able to create `v1alpha1`  `CSPC`

If the system has both `v1` or `v1alpha1` of `CSPC` and metacontroller has 1 config file it will be not be able to create `CSPC`

If the system has both `v1` and `v1alpah1` of `CSPC` and metacontroller has 1 config file it will be able to create both `v1` and `v1alpha1`  `CSPC`

**Comment by AmitKumarDas** [comment]
Alright to clear my confusion, I believe a single config instance will never work. It will work based on the attachment apiversion set. Also each version is set to different sync hooks. On the whole there is no concept of single config instance.

**Pull request merged**
